#!/usr/bin/env python3
"""OD17/OD18 (tma-relume-redesign, T-1146/T-1147) — сборка субсета шрифта.

Идемпотентно и ОФФЛАЙН: из тяжёлого исходника Material Symbols Rounded
(``MaterialSymbolsRounded[FILL,GRAD,opsz,wght].woff2``, ~5.11 МиБ в корне)
собирает лёгкий субсет (~единицы-десятки КБ) с нужными иконками (37 в 10.8).

Пайплайн (design-project.md §15.4.1):
  1. PUA-кодпоинты иконок выводятся из самого шрифта (GSUB-лигатуры ->
     reverse-cmap), без сети и без ``.codepoints``.
  2. ``fontTools.varLib.instancer``: pin GRAD=0, opsz=24; оставить FILL
     переменной (для ``is-active``), wght — переменной.
  3. ``fontTools.subset``: по PUA-кодпоинтам -> ``--flavor=woff2``.

ВАЖНО: ``--unicodes-file`` НЕ сохраняет лигатуры (``rlig/rclt`` -> 0) ⟹
иконки адресуются PUA-кодпоинтом (``&#xE850;`` / CSS ``content:"\\e850"``),
а не текстовым именем (см. §15.4.4).

Зависимости — BUILD-TIME ONLY (``scripts/requirements-font.txt``:
``fonttools[woff]`` + ``brotli``); в runtime-``requirements.txt`` НЕ входят
(OD17). Запуск::

    python scripts/build_font_subset.py

В git коммитим ТОЛЬКО результат (``web/static/fonts/material-symbols-rounded.woff2``
+ ``LICENSE-material-symbols.txt``); исходник 5.11 МиБ — ``.gitignore``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE_CANDIDATES = (
    ROOT / "MaterialSymbolsRounded[FILL,GRAD,opsz,wght].woff2",
    ROOT / "web" / "static" / "fonts" / "source"
    / "MaterialSymbolsRounded[FILL,GRAD,opsz,wght].woff2",
)
OUT_WOFF2 = ROOT / "web" / "static" / "fonts" / "material-symbols-rounded.woff2"
OUT_LICENSE = ROOT / "web" / "static" / "fonts" / "LICENSE-material-symbols.txt"
BUILD_DIR = ROOT / "build"

# Иконки мини-аппа (design-project.md §5.4; раунд 10.8 §2.2/§3.2).
# Паритет: множество имён ОБЯЗАНО совпадать с ключами `var ICONS` в web/app.js
# (ADR-002, тест test_font_subset). 20 базовых + 17 новых 10.8 = 37.
ICON_NAMES: tuple[str, ...] = (
    "admin_panel_settings", "auto_stories", "badge", "bedtime", "bolt",
    "chevron_right", "cloud", "delete", "description", "dns", "edit_note",
    "expand_more", "extension", "grid_view", "group", "help", "history",
    "key", "manage_accounts", "memory", "monitoring", "play_arrow",
    "play_circle", "psychology", "radar", "receipt_long", "restart_alt",
    "save", "settings", "shield", "smart_toy", "stop", "supervisor_account",
    "swap_horiz", "trending_up", "visibility", "visibility_off",
)
ICON_CODEPOINTS_JSON = BUILD_DIR / "icon_codepoints.json"

LICENSE_TEXT = """Material Symbols Rounded
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

This repository ships a SUBSET of the font (generated by
scripts/build_font_subset.py, Apache-2.0); the full source font is NOT
committed (see .gitignore). Upstream:
https://github.com/google/material-design-icons
"""


def find_source() -> Path:
    for cand in SOURCE_CANDIDATES:
        if cand.exists():
            return cand
    raise SystemExit(
        "Исходник шрифта не найден. Положите "
        "'MaterialSymbolsRounded[FILL,GRAD,opsz,wght].woff2' в корень проекта.")


def derive_pua_codepoints(source: Path) -> dict[str, int]:
    """PUA-кодпоинт каждой иконки из GSUB-лигатур (оффлайн, без .codepoints)."""
    from fontTools.ttLib import TTFont
    font = TTFont(str(source))
    cmap = font.getBestCmap()
    glyph_to_cp: dict[str, int] = {}
    for cp, gname in cmap.items():
        glyph_to_cp.setdefault(gname, cp)
    ascii_by_glyph = {g: chr(cp) for cp, g in cmap.items() if 0x20 <= cp <= 0x7E}
    ligatures: dict[str, str] = {}
    for lookup in font["GSUB"].table.LookupList.Lookup:
        for st in lookup.SubTable:
            if type(st).__name__ == "ExtensionSubst":
                st = st.ExtSubTable
            if type(st).__name__ != "LigatureSubst":
                continue
            for first, lig_set in st.ligatures.items():
                for lig in lig_set:
                    comps = [first] + list(lig.Component)
                    name = "".join(
                        ascii_by_glyph.get(c, "?") for c in comps)
                    ligatures[name] = lig.LigGlyph
    result: dict[str, int] = {}
    missing: list[str] = []
    for name in ICON_NAMES:
        glyph = ligatures.get(name) or ligatures.get(name.replace("_", ""))
        cp = glyph_to_cp.get(glyph) if glyph else None
        if cp is None:
            missing.append(name)
        else:
            result[name] = cp
    if missing:
        raise SystemExit(f"Не найдены кодпоинты иконок: {missing}")
    return result


def _marker_key(src_sha: str) -> str:
    """Ключ идемпотентности: sha исходника + список ICON_NAMES.

    Правка ICON_NAMES НЕ меняет sha исходника — без учёта списка скрипт
    ошибочно считал бы субсет актуальным и не пересобирал новые глифы
    (spec 10.8 §2.4, ADR-002 п.3)."""
    payload = src_sha + "|" + ",".join(ICON_NAMES)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _write_icon_codepoints(codepoints: dict[str, int]) -> None:
    """build/icon_codepoints.json: {name: 'U+XXXX'} (сортировка по имени)."""
    data = {name: f"U+{codepoints[name]:04X}" for name in sorted(codepoints)}
    ICON_CODEPOINTS_JSON.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"[font] codepoints -> {ICON_CODEPOINTS_JSON}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Material Symbols subset builder")
    parser.add_argument("--source", type=Path, default=None)
    args = parser.parse_args()

    source = args.source or find_source()
    src_bytes = source.read_bytes()
    src_sha = hashlib.sha256(src_bytes).hexdigest()
    print(f"[font] source: {source} ({len(src_bytes)} B, sha256={src_sha[:12]}…)")

    marker_key = _marker_key(src_sha)
    marker = BUILD_DIR / "font_source.sha256"
    if (OUT_WOFF2.exists() and marker.exists()
            and marker.read_text().strip() == marker_key):
        print(f"[font] up-to-date subset already built: {OUT_WOFF2}")
        if not ICON_CODEPOINTS_JSON.exists():
            BUILD_DIR.mkdir(parents=True, exist_ok=True)
            _write_icon_codepoints(derive_pua_codepoints(source))
        _write_license()
        return 0

    codepoints = derive_pua_codepoints(source)
    BUILD_DIR.mkdir(parents=True, exist_ok=True)
    _write_icon_codepoints(codepoints)
    unicodes_file = BUILD_DIR / "subset_unicodes.txt"
    unicodes_file.write_text(
        "\n".join(f"U+{cp:04X}" for cp in sorted(codepoints.values())),
        encoding="utf-8")
    print(f"[font] {len(codepoints)} icons -> {unicodes_file}")

    instanced = BUILD_DIR / "msr-instanced.ttf"
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer
    from fontTools.subset import main as subset_main

    font = TTFont(str(source))
    instancer.instantiateVariableFont(
        font, {"GRAD": 0, "opsz": 24}, inplace=True, updateFontNames=False)
    font.save(str(instanced))
    print(f"[font] instanced (GRAD=0, opsz=24; FILL/wght variable) -> {instanced}")

    OUT_WOFF2.parent.mkdir(parents=True, exist_ok=True)
    # subset CLI-эквивалент; пишем во временный буфер через argv.
    argv = [
        str(instanced),
        "--output-file=" + str(OUT_WOFF2),
        "--flavor=woff2",
        "--unicodes-file=" + str(unicodes_file),
        "--no-hinting",
        "--desubroutinize",
    ]
    rc = subset_main(argv)
    if rc not in (0, None):
        raise SystemExit(f"fontTools.subset вернул код {rc}")
    _write_license()
    marker = BUILD_DIR / "font_source.sha256"
    marker.write_text(marker_key, encoding="utf-8")
    size = OUT_WOFF2.stat().st_size if OUT_WOFF2.exists() else -1
    print(f"[font] subset built: {OUT_WOFF2} ({size} B)")
    return 0


def _write_license() -> None:
    OUT_LICENSE.parent.mkdir(parents=True, exist_ok=True)
    if not OUT_LICENSE.exists():
        OUT_LICENSE.write_text(LICENSE_TEXT, encoding="utf-8")
        print(f"[font] LICENSE written: {OUT_LICENSE}")


if __name__ == "__main__":
    sys.exit(main())
