# -*- coding: utf-8 -*-
"""Одноразовый скрипт: README changelog ASAP-3.1 (блок N)."""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
p = ROOT / "README.md"
text = p.read_text(encoding="utf-8")

old_head = "**Версия:** v2.58.36 | **Раунд:**"
assert old_head in text, "README: заголовок версии не найден"

new_head = (
    "**Версия:** v2.58.37 | **Раунд:** 10.28 ASAP-3.1 "
    "`mca-asap31-auto-budgets-capacity-react` — corrective acceptance "
    "addendum после ASAP-3 (P0 владельца, current_task.md «# ASAP-3.1» "
    "§1–§146, spec CC419781 + ADR-1028-3 D1–D8). (1) Model Capacity Resolver "
    "(`services/model_capacity.py`): precedence developer_override "
    "(`models.chat_context_window_override`, 0=Auto) → runtime-адаптеры "
    "(llama.cpp `/props`, Ollama, vLLM config introspection) → provider "
    "catalog (OpenRouter `context_length`) → verified registry (+deepseek-v4/"
    "deepseek-flash) → консервативный fallback ТОЛЬКО аварийно (WARNING "
    "`MODEL_CAPACITY_FALLBACK` + badge «не подтверждено»); unknown-модель "
    "больше не получает молчаливый 16384 как нормальный путь; effective = "
    "min(runtime, declared); TTL-кэш (remote 24 ч / локальные 300 с, "
    "`MODEL_CAPACITY_CACHE_TTL_SECONDS` env-only), инвалидация по ключу "
    "model/base_url/override + refresh. (2) Единый Stage Auto Budget "
    "Resolver (`services/auto_budget.py`): формула window − mandatory − "
    "output_reserve(stage) − safety ×1; output reserve stage-aware (Direct "
    "0.10, Summary L1 4000 / L2 6000); Dynamic 16000 — operational soft "
    "target, НЕ hard scissors (§35); стадии — через registry-policy "
    "(summary.l1 exhaustive/chunk_all, direct.primary relevance_composed). "
    "Потребители: Direct композер, Summary L1/L2, fallback recompose, "
    "`/api/analytics/context-budgets`, Status — ОДИН источник цифр (второго "
    "usage store нет). (3) Summary Window = полный охват (§118–§146): окно "
    "определяет source set; при физическом переполнении — lossless "
    "chunking (serialized-партиции, overlap=1, oversized-сообщение — свой "
    "chunk без text[:N]) + детерминированный merge L1 (cross-chunk темы "
    "объединяются по stable-ID overlap, дедуп); coverage-метрики "
    "(source/processed/chunks/coverage%), события SUMMARY_L1_CHUNKED/"
    "SUMMARY_COVERAGE_DEGRADED; семантика «skipped=N» из-за бюджета "
    "устранена на ON-пути; timeout ≠ drop (retry → fallback → fail-soft "
    "package из ПОЛНОГО набора); инцидент 21001 устранён (legacy static "
    "30000-путь только на kill-switch OFF); manual cap = размер ОДНОГО "
    "L1-запроса. (4) LLM REACT: при action=REACT конкретный emoji выбирает "
    "LLM в том же Stage-1 (аддитивный блок <Reaction_Task>, allowed set = "
    "10 Telegram-emoji, стандарт расширен 9→11: 💀🤡); невалидно/нет → "
    "детерминированный fallback fail-soft; матрица сохраняет владение "
    "action (await_count==2, второго LLM request нет); SILENT→🗿 — "
    "единственный hardcode; Force keyword → всегда REPLY; kill-switch "
    "`DIRECT_LLM_REACTION_ENABLED` + per-chat flags → OFF = прежний "
    "детерминированный шорт-кат. (5) Miniapp/Analytics/Status: разводка "
    "тумблера «Безлимит» → «Без суточных квот» (только 4 quota-ключа) + "
    "Context Mode (context ≠ quota ≠ worker, миграция non-destructive); "
    "страница «Бюджеты» — read-only карточка автобюджетов активных слотов "
    "(наследование компактной строкой, fallback-warning); Advanced — "
    "ручное окно модели (0=Авто, «Auto detected: …»); Analytics — секция "
    "«Модели и автобюджеты» (human-first, source-бейджи по-русски, "
    "fail-open по блокам); Status — компакт «Бюджеты интеллекта» из того "
    "же resolver'а. (6) Frontend corrective: «Аналитика» возвращена в "
    "навигацию IA v2 (`NAV_ITEMS_V2` + oversight; desktop sidebar + "
    "«Ещё», один route `#/oversight`, RBAC global admin); Polygon — "
    "устранена первопричина мерцания (rebuild 4 Hz + fade-reset заменён "
    "редким displacement-порогом/crossfade 4 c с полом яркости 0.85; "
    "амплитуды узлов/halo снижены: база ≥0.80, свинг ≤10%), живая форма — "
    "scene seed через crypto.getRandomValues (каждая загрузка — новая "
    "композиция: центр/масштаб/кластеры), медленный глобальный дрейф, "
    "?bgseed/start({seed}) — детерминизм тестов, getDiagnostics +8 полей; "
    "bottom nav — единая модель геометрии (shell = фактически видимая "
    "высота Telegram/visualViewport без guessed-offset, inset РОВНО ОДИН "
    "раз на панели). (7) Observability: события 28→33 (+"
    "MODEL_CAPACITY_RESOLVED/AUTO_CONTEXT_BUDGET/DIRECT_REACT/"
    "SUMMARY_L1_CHUNKED/SUMMARY_COVERAGE_DEGRADED, R17-whitelist) + "
    "счётчики §50 (capacity fallback/manual override/pressure/overflow/"
    "react distribution — process-local, grep-able); migration "
    "custom-preserved → INFO `CONFIG_MIGRATION_CUSTOM_PRESERVED`. "
    "(8) Каталог: санкция spec 10.1 — +1 ключ `models.chat_context_window_"
    "override` (Settings 423→424) + 6 переименований labels/группы "
    "(tokens ≠ «слова») → 484/424/459/105/103/21, F8 переиздан атомарно. "
    "Δ DDL=0, Δ внешних зависимостей=0, R17/R18. Откат: soft — 7 env-only "
    "kill-switch'ей (MODEL_CAPACITY_RESOLVER_ENABLED, AUTO_BUDGET_RESOLVER_"
    "ENABLED, SUMMARY_COVERAGE_CHUNKING_ENABLED, DIRECT_LLM_REACTION_"
    "ENABLED, UI_BUDGETS_SPLIT_ENABLED, ANALYTICS_CONTEXT_BUDGETS_ENABLED, "
    "CONFIG_MIGRATION_INFO_LOGGING_ENABLED — каждый OFF = байт-в-байт "
    "прежний путь); Polygon/bottom-nav — без флагов (cold revert); cold — "
    "revert до тега `pre-2.58.37` (прод-базис 2.58.36, `c5cb5a9`). bump "
    "2.58.36 → 2.58.37. Ранее 10.27 MCA wave-package-release "
    "`mca-wave-package-release-1027` §93–§100"
)
text = text.replace(old_head, new_head, 1)
p.write_text(text, encoding="utf-8")
print("README updated")
